"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Row = Record<string, string | number | boolean | null>;
const roles: Record<string,string> = { admin:"Quản trị viên", homeroom:"GVCN", subject:"GV bộ môn", representative:"Đại diện lớp" };

export default function AdminManager() {
  const [tab,setTab]=useState("classes"); const [data,setData]=useState<{users:Row[];classes:Row[];students:Row[];permissions:Row[]}>({users:[],classes:[],students:[],permissions:[]}); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{ const response=await fetch("/api/admin"); const result=await response.json(); if(response.ok)setData(result); else setError(result.error); },[]);
  useEffect(()=>{load()},[load]);
  const submit=async(event:FormEvent<HTMLFormElement>,action:string)=>{event.preventDefault();setBusy(true);setError("");const values=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...values,canUpdate:values.canUpdate==="on"})});const result=await response.json();setBusy(false);if(!response.ok)return setError(result.error);event.currentTarget.reset();await load()};
  const disable=async(type:string,id:number)=>{if(!confirm("Bạn chắc chắn muốn khóa mục này?"))return;await fetch(`/api/admin?type=${type}&id=${id}`,{method:"DELETE"});await load()};
  return <div className="manager">
    <div className="manager-tabs">{[["classes","Lớp học"],["students","Học sinh"],["users","Tài khoản"],["permissions","Phân quyền"]].map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</div>
    {error&&<div className="manager-error">{error}{error.includes("DATABASE_URL")&&<small>Hãy thêm DATABASE_URL trên Vercel rồi Redeploy.</small>}</div>}
    {tab==="classes"&&<div className="manager-layout"><form onSubmit={e=>submit(e,"createClass")}><h3>Tạo lớp mới</h3><label>Tên lớp<input name="name" required placeholder="Ví dụ: 10A1"/></label><label>Khối<input name="grade" placeholder="Ví dụ: 10"/></label><label>Giáo viên chủ nhiệm<select name="teacherId"><option value="">Chưa phân công</option>{data.users.filter(u=>u.role==="homeroom").map(u=><option key={String(u.id)} value={String(u.id)}>{String(u.name)}</option>)}</select></label><button disabled={busy}>Tạo lớp</button></form><DataTable rows={data.classes} columns={[["name","Lớp"],["grade","Khối"],["homeroom_teacher","GVCN"]]} onDisable={id=>disable("class",id)}/></div>}
    {tab==="students"&&<div className="manager-layout"><div><form onSubmit={e=>submit(e,"createStudent")}><h3>Thêm học sinh</h3><label>Mã học sinh<input name="code" required/></label><label>Họ và tên<input name="name" required/></label><ClassSelect classes={data.classes} name="classId"/><button disabled={busy}>Thêm học sinh</button></form><form className="import-form" onSubmit={e=>submit(e,"importStudents")}><h3>Dán danh sách</h3><ClassSelect classes={data.classes} name="classId"/><textarea name="list" required rows={5} placeholder={'HS001; Nguyễn Văn A\nHS002; Trần Thị B'}/><button disabled={busy}>Nhập danh sách</button></form></div><DataTable rows={data.students} columns={[["student_code","Mã"],["name","Học sinh"],["class_name","Lớp"]]} onDisable={id=>disable("student",id)}/></div>}
    {tab==="users"&&<div className="manager-layout"><form onSubmit={e=>submit(e,"createUser")}><h3>Tạo tài khoản</h3><label>Họ và tên<input name="name" required/></label><label>Tên đăng nhập<input name="username" required/></label><label>Mật khẩu<input name="password" type="password" minLength={8} required/></label><label>Vai trò<select name="role">{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button disabled={busy}>Tạo tài khoản</button></form><DataTable rows={data.users} columns={[["username","Tài khoản"],["name","Họ tên"],["role","Vai trò"]]} onDisable={id=>disable("user",id)} role/></div>}
    {tab==="permissions"&&<div className="manager-layout"><form onSubmit={e=>submit(e,"grantPermission")}><h3>Cấp quyền theo lớp</h3><label>Người dùng<select name="userId" required><option value="">Chọn tài khoản</option>{data.users.map(u=><option key={String(u.id)} value={String(u.id)}>{String(u.name)} · {roles[String(u.role)]}</option>)}</select></label><ClassSelect classes={data.classes} name="classId"/><label className="check"><input name="canUpdate" type="checkbox"/> Cho phép cập nhật</label><button disabled={busy}>Lưu quyền</button></form><DataTable rows={data.permissions} columns={[["user_name","Người dùng"],["class_name","Lớp"],["can_update","Quyền cập nhật"]]}/></div>}
  </div>;
}
function ClassSelect({classes,name}:{classes:Row[];name:string}){return <label>Lớp<select name={name} required><option value="">Chọn lớp</option>{classes.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label>}
function DataTable({rows,columns,onDisable,role}:{rows:Row[];columns:string[][];onDisable?:(id:number)=>void;role?:boolean}){return <div className="manager-table"><div className="manager-tr head">{columns.map(c=><span key={c[0]}>{c[1]}</span>)}{onDisable&&<span/>}</div>{rows.length===0?<div className="manager-empty">Chưa có dữ liệu</div>:rows.map(row=><div className="manager-tr" key={String(row.id)}>{columns.map(c=><span key={c[0]}>{role&&c[0]==="role"?roles[String(row[c[0]])]:typeof row[c[0]]==="boolean"?(row[c[0]]?"Có":"Không"):String(row[c[0]]??"—")}</span>)}{onDisable&&<button onClick={()=>onDisable(Number(row.id))}>Khóa</button>}</div>)}</div>}
