export type AppRole = "admin" | "homeroom" | "subject" | "representative";
export type AppUser = { username: string; password: string; name: string; role: AppRole };
const encoder = new TextEncoder();
const toBase64 = (value: Uint8Array) => btoa(String.fromCharCode(...value)).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
const fromBase64 = (value: string) => Uint8Array.from(atob(value.replaceAll("-", "+").replaceAll("_", "/")), (char) => char.charCodeAt(0));
const users = (): AppUser[] => { try { const value = JSON.parse(process.env.APP_USERS_JSON || "[]"); if (Array.isArray(value) && value.length) return value; } catch {} return process.env.NODE_ENV !== "production" ? [{ username: "admin", password: "admin123", name: "Quản trị hệ thống", role: "admin" }] : []; };
const secret = () => process.env.SESSION_SECRET || (process.env.NODE_ENV !== "production" ? "fschool-local-development-secret" : "");
export function authenticate(username: string, password: string) { const user = users().find((item) => item.username === username && item.password === password); if (!user) return null; const { password: _, ...safe } = user; return safe; }
export async function createSession(user: Omit<AppUser, "password">) { if (!secret()) throw new Error("Missing secret"); const payload = toBase64(encoder.encode(JSON.stringify({ ...user, exp: Date.now() + 28800000 }))); const key = await crypto.subtle.importKey("raw", encoder.encode(secret()), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const signature = await crypto.subtle.sign("HMAC", key, encoder.encode(payload)); return `${payload}.${toBase64(new Uint8Array(signature))}`; }
export async function readSession(token?: string | null) { if (!token || !secret()) return null; const [payload, signature] = token.split("."); if (!payload || !signature) return null; const key = await crypto.subtle.importKey("raw", encoder.encode(secret()), { name: "HMAC", hash: "SHA-256" }, false, ["verify"]); if (!await crypto.subtle.verify("HMAC", key, fromBase64(signature), encoder.encode(payload))) return null; const data = JSON.parse(new TextDecoder().decode(fromBase64(payload))); return data.exp > Date.now() ? data : null; }
